apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/thewell-nfs-client-provisioner
  labels:
    app.kubernetes.io/name: zoneminder
  name: zoneminder
  namespace: zoneminder
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client