# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt
#   namespace: cert-manager
# spec:
#   acme:
#     email: scott@stevelinck.com
#     privateKeySecretRef:
#       name: letsencrypt-prod-wildcard
#     server: https://acme-v02.api.letsencrypt.org/directory
#     solvers:
#     - dns01:
#         cloudflare:
#           apiTokenSecretRef:
#             key: api-token
#             name: cloudflare-api-token-secret
#           email: scott@stevelinck.com

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: scott@stevelinck.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: traefik
