apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-services-bitwarden
  name: bitwarden
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-services-bitwarden
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-services-bitwarden
    spec:
      containers:
      - env:
        - name: YUBICO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client_id
              name: yubikey
              optional: false
        - name: YUBICO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret
              name: yubikey
              optional: false        
        - name: ROCKET_PORT
          value: "8000"
        image: vaultwarden/server
        imagePullPolicy: IfNotPresent
        name: bitwarden
        ports:
        - containerPort: 8000
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: "2.5"
            memory: "512M"
          requests:
            cpu: "2.0"
            memory: "512M"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: bitwarden-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: bitwarden-data
        persistentVolumeClaim:
          claimName: bitwarden-data