apiVersion: v1
kind: Service
metadata:
  name: bitwarden-load-balancer
  namespace: services
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8000
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000

  selector:
    workload.user.cattle.io/workloadselector: deployment-services-bitwarden
  sessionAffinity: None
  type: LoadBalancer

