apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-services-heimdall
  name: heimdall
  namespace: services
spec:
  replicas: 2
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-services-heimdall
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-services-heimdall
    spec:
      containers:
      - env:
        - name: PGID
          value: "65534"
        - name: PUID
          value: "65534"
        - name: TZ
          value: Americas/Denver
        image: linuxserver/heimdall
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: heimdall
        ports:
        - containerPort: 80
          name: heimdall-http
          protocol: TCP
        - containerPort: 443
          name: heimdall-https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources:
          limits:
            cpu: "1.0"
            memory: "512M"
          requests:
            cpu: "2.0"
            memory: "512M"
        volumeMounts:
        - mountPath: /config
          name: heimdall
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: heimdall
        persistentVolumeClaim:
          claimName: heimdall
