apiVersion: v1
kind: Service
metadata:
  name: heimdall-load-balancer
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-heimdall
  sessionAffinity: None
  type: LoadBalancer

