apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/thewell-nfs-client-provisioner
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/name: heimdall
  name: heimdall
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client