apiVersion: v1
kind: Service
metadata:
  name: unifi-video-loadbalancer
  namespace: unifi
  annotations:
    external-dns.alpha.kubernetes.io/hostname: unifivideo.internal
spec:
  ports:
  - name: https
    nodePort: 31169
    port: 443
    protocol: TCP
    targetPort: 7443
  - name: 7445tcp74453
    nodePort: 32432
    port: 7445
    protocol: TCP
    targetPort: 7445
  - name: 7446tcp74463
    nodePort: 31187
    port: 7446
    protocol: TCP
    targetPort: 7446
  - name: 7447tcp74473
    nodePort: 30739
    port: 7447
    protocol: TCP
    targetPort: 7447
  - name: 7442tcp74423
    nodePort: 31539
    port: 7442
    protocol: TCP
    targetPort: 7442
  - name: 6666tcp66663
    nodePort: 32161
    port: 6666
    protocol: TCP
    targetPort: 6666
  - name: 7080tcp70803
    nodePort: 32363
    port: 7080
    protocol: TCP
    targetPort: 7080
  - port: 1935
    targetPort: 1935
    name: rtmp
    protocol: TCP
  - port: 7444
    targetPort: 7444
    name: rtmps
    protocol: TCP   
  selector:
    workload.user.cattle.io/workloadselector: deployment-unifi-unifi-video
  sessionAffinity: None
  type: LoadBalancer
  externalTrafficPolicy: Local

