apiVersion: v1
kind: Service
metadata:
  name: powerdns-admin-loadbalancer
  namespace: external-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: powerdns-admin.internal
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9191
  selector:
    workload.user.cattle.io/workloadselector: deployment-powerdns-admin
  sessionAffinity: None
  type: LoadBalancer

