apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powerdns-admin
  namespace: external-dns
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
