---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-loadbalancer
  namespace: services
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app.kubernetes.io/instance: mosquitto
  sessionAffinity: None
  type: LoadBalancer
