apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: traefik
  name: local.stevelinck.com
  namespace: traefik
spec:
  commonName: local.stevelinck.com
  dnsNames:
    - local.stevelinck.com
    - '*.local.stevelinck.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: local.stevelinck.com