---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik-config.yaml: |
    http:
      services:
        homeassistant:
          loadBalancer:
            servers:
            - url: "http://192.168.1.93:8123"
        rockstor:
          loadBalancer:
            servers:
            - url: "https://192.168.1.145"
