---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: traefik
  name: homeassistant-http
  namespace: services
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`ha.internal`)
      services:
        - kind: TraefikService
          name: homeassistant@file
          port: 80
          scheme: http

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: traefik
  name: homeassistant-https
  namespace: services
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ha.internal`, `ha.stevelinck.com`)
      middlewares:
        - name: crowdsec-auth
      services:
        - kind: TraefikService
          name: homeassistant@file
          port: 80
          scheme: http
  tls: {}
