---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influxdb
  namespace: services
  annotations:  
    kubernetes.io/ingress.class: traefik-cert-manager
spec:
  tls:
    - hosts:
      - influxdb.local.stevelinck.com
  rules:
    - host: influxdb.local.stevelinck.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: influxdb
              port:
                number: 8086