---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:  
    kubernetes.io/ingress.class: traefik-cert-manager
spec:
  tls:
    - hosts:
      - longhorn.local.stevelinck.com
  rules:
    - host: longhorn.local.stevelinck.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: longhorn-frontend
              port:
                number: 80