---
apiVersion: v1
kind: Service
metadata:
  name: argocd-loadbalancer
  namespace: argocd
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30853
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31671
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: LoadBalancer
