---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-unifi-unifi-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-unifi-unifi-controller
    spec:
      tolerations:
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        tolerationSeconds: 0
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        tolerationSeconds: 0
      containers:
      - env:
        - name: MEM_LIMIT
          value: 1024M
        - name: PGID
          value: "65534"
        - name: PUID
          value: "65534"
        image: linuxserver/unifi-controller:6.4.54
        imagePullPolicy: Always
        name: unifi-controller
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 3478
          name: 3478udp3478
          protocol: UDP
        - containerPort: 10001
          name: 10001udp10001
          protocol: UDP
        resources:
          limits:
            cpu: "0.5"
            memory: "1G"
        volumeMounts:
        - mountPath: /config
          name: unifi-controller
          subPath: "20211012"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: unifi-controller
        persistentVolumeClaim:
          claimName: unifi-controller
