---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-loadbalancer
  namespace: unifi
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31686
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 32332
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-unifi-unifi-controller
  sessionAffinity: None
  type: LoadBalancer
