---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-loadbalancer
  namespace: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: unificontroller
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.3.233
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31686
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 32332
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-unifi-unifi-controller
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-udp
  namespace: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: unificontroller
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.3.233
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: stun
    port: 3478
    protocol: UDP
    targetPort: 3478
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-unifi-unifi-controller
  sessionAffinity: None
  type: LoadBalancer