apiVersion: v1
kind: Service
metadata:
  name: transmission-load-balancer
  namespace: transmission
  annotations:
    external-dns.alpha.kubernetes.io/hostname: transmission.internal
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9091
  selector:
    app: transmission
  sessionAffinity: None
  type: LoadBalancer

