apiVersion: v1
kind: Service
metadata:
  name: transmission-load-balancer
  namespace: transmission
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9091
  selector:
    workload.user.cattle.io/workloadselector: deployment-transmission
  sessionAffinity: None
  type: LoadBalancer

