apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/thewell-nfs-client-provisioner
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/name: transmission-data
  name: transmission-data
  namespace: transmission
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-client