apiVersion: v1
kind: Service
metadata:
  name: kuma
  namespace: services
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kuma.internal
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    workload.user.cattle.io/workloadselector: deployment-kuma
  sessionAffinity: None
  type: LoadBalancer
  externalTrafficPolicy: Local

