apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: nginx
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-nginx-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2021-10-13T00:45:52Z"
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-nginx-db
    spec:
      affinity: {}
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db.root-password
              name: nginx-proxy-manager
              optional: false
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: db.name
              name: nginx-proxy-manager
              optional: false
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: db.user
              name: nginx-proxy-manager
              optional: false
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db.password
              name: nginx-proxy-manager
              optional: false
        image: jc21/mariadb-aria:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        name: db
        ports:
        - containerPort: 3306
          name: db
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db
          subPath: db
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: db
