apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: services-traefik-crowdsec-auth
  namespace: traefik
spec:
  forwardAuth:
    address: >-
      http://traefik-crowdsec-bouncer.crowdsec.svc.cluster.local:8080/api/v1/forwardAuth
