apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-crowdsec-bouncer
  namespace: crowdsec
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-traefik-crowdsec-bouncer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-traefik-crowdsec-bouncer
    spec:
      containers:
      - env:
        - name: CROWDSEC_BOUNCER_API_KEY
          valueFrom:
            secretKeyRef:
              name: crowdsec-api
              key: api_key
        - name: CROWDSEC_AGENT_HOST
          value: "8080"
        - name: CROWDSEC_BOUNCER_SCHEME
          value: http
        - name: GIN_MODE
          value: debug
        image: fbonalair/traefik-crowdsec-bouncer
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 2
        name: traefik-crowdsec-bouncer
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 2
        resources:
          limits:
            cpu: "1.0"
            memory: "128M"
          requests:
            cpu: "0.5"
            memory: "128M"
      dnsPolicy: ClusterFirst
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: traefik-crowdsec-bouncer
  namespace: crowdsec
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-traefik-crowdsec-bouncer
  sessionAffinity: None
  type: Cluster
